name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

      steps:
        - name: Clone repository
          uses: actions/checkout@v4.1.1

        - name: Set up Java 21
          uses: actions/setup-java@v4.2.1
          with:
            java-version: 21
            distribution: 'zulu'
        - name: Publish to GitHub Packages Apache Maven
          run: mvn clean deploy -P release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}