name: Run tests

on:
  workflow_dispatch:

jobs:
 autotests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1

      - name: Set up Java 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Run Test
        run: mvn test
