name: Maven Test

on:
  push:
    branches: [ main ]

jobs:
 autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1

      - name: Set up Java 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Run Test
        run: mvn test
